name: Broken scraper report
description: Report a scraper that is not working as expected.
labels: ["bug"]
body:
  - type: input
    id: package-name
    attributes:
      label: Package name of the scraper
      description: Go to Settings > Metadata Providers > Installed Scrapers and under "Package" column, find the package name of the scraper.
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Scraper version
      description: Go to Settings > Metadata Providers > Installed Scrapers and under "Installed version" column, find the version of the scraper.
    validations:
      required: true
  - type: dropdown
    id: scraper-type
    attributes:
      label: Which scraper types are affected?
      description: You can select more than one.
      multiple: true
      options:
        - performerByName
        - performerByFragment
        - performerByURL
        - sceneByName
        - sceneByQueryFragment
        - sceneByFragment
        - sceneByURL
        - groupByURL
        - galleryByFragment
        - galleryByURL
        - imageByFragment
        - imageByURL
    validations:
      required: true
  - type: textarea
    id: scraper-type-details
    attributes:
      label: Scraper type specific details
      description: |
        Please provide additional details that may be relevant. For example:
        - For "\<object\>ByURL" scrapers, please provide an example URL that you would want to be able to scrape with that scraper.  
        - For "\<object\>ByFragment" scrapers, please provide the details about which fragment you would want that scraper to use.  
        - For "\<object\>ByName" scrapers, please provide an example of an "\<object\>" name that you would want to be able to scrape with that scraper.

        \<object\> can be performer, scene, group, gallery, or image depending on the scraper type.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide any relevant logs that may help in diagnosing the issue with the scraper. 
        
        You can find the logs in Stash under Settings > Logs. Make sure to set the Log Level to Debug to get the most detailed logs.
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Additional details
      description: |
        If there are any additional details about the issue that you think may be relevant, please provide them here.
    validations:
      required: false
  - type: checkboxes
    id: confirm-search
    attributes:
      label: Have you looked at existing bug reports?
      description: |
        Please ensure you have first [searched existing bug reports](https://github.com/stashapp/CommunityScrapers/issues?q=is%3Aissue%20label%3Abug) to make sure your report is not a duplicate.
      options:
        - label: I have searched the existing bug reports.
          required: true