blank_issues_enabled: false
contact_links:
  - name: Existing scraper list
    url: https://stashapp.github.io/CommunityScrapers
    about: Searchable list of existing scrapers with additional details.
  - name: Community forum
    url: https://discourse.stashapp.cc
    about: Start a discussion on the community forum.
  - name: Community Discord
    url: https://discord.gg/Y8MNsvQBvZ
    about: Chat with the community on Discord.
  - name: Stash documentation
    url: https://docs.stashapp.cc
    about: Check out Stash documentation for help and information.