name: Validate Scrapers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: denoland/setup-deno@v2
      with:
        cache: true
    - run: deno -R -E ./validate.js --ci
